//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetFinanceVoucherRecord
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public Nullable<int> CurrentVoucherNo { get; set; }
    }
}
