//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetSession()
        {
            this.AspNetStudent_Term_Assessment = new HashSet<AspNetStudent_Term_Assessment>();
            this.AspNetTerms = new HashSet<AspNetTerm>();
        }
    
        public int Id { get; set; }
        public string SessionName { get; set; }
        public Nullable<System.DateTime> SessionStartDate { get; set; }
        public Nullable<System.DateTime> SessionEndDate { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Term_Assessment> AspNetStudent_Term_Assessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetTerm> AspNetTerms { get; set; }
    }
}
