//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetFinanceVoucherDetail
    {
        public int Id { get; set; }
        public Nullable<int> LedgertypeId { get; set; }
        public Nullable<int> LedgerId { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<double> Debit { get; set; }
        public string TransactionDescription { get; set; }
        public Nullable<int> VoucherId { get; set; }
    
        public virtual AspNetFinanceLedger AspNetFinanceLedger { get; set; }
        public virtual AspNetFinanceLedgerType AspNetFinanceLedgerType { get; set; }
        public virtual AspNetFinanceVoucher AspNetFinanceVoucher { get; set; }
    }
}
