//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttandence
    {
        public int EAttandenceID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
