//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeWork
    {
        public int HWID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string HWDetail { get; set; }
        public Nullable<int> DiaryID { get; set; }
    
        public virtual Diary Diary { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
