//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageReceiver
    {
        public int ReceiverID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> MessageID { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual User User { get; set; }
    }
}
