//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttandence
    {
        public int SAttandenceID { get; set; }
        public Nullable<int> AttandenceID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
    
        public virtual Attendance Attendance { get; set; }
        public virtual Student Student { get; set; }
    }
}
